import { useMemo, useState } from 'react'
import {
  AlertTriangle, ArrowRight, Bell, CalendarDays, CheckCircle2, ChevronDown,
  CircleHelp, Clock3, Download, FileUp, Filter, MoreHorizontal, Play,
  Plus, Search, Settings2, ShieldCheck, Sparkles, Upload, Users, X,
} from 'lucide-react'
import './App.css'

type View = 'Dashboard' | 'AI Insights' | 'Processing Periods' | 'Data Import Centre' | 'Attendance Register' | 'Exception Workbench' | 'Approval Inbox' | 'Leave & OD' | 'Comp-Off' | 'Payroll Register' | 'Rule Configuration' | 'User & Role Management' | 'Integration Settings' | 'Reports' | 'Audit Trail'
type Toast = { message: string; kind?: 'success' | 'warning' } | null
type Persona = 'HR Operations Lead' | 'HR Manager' | 'VP of HR' | 'CHRO'

const nav: { label: View; group?: string }[] = [
  { label: 'Dashboard' }, { label: 'AI Insights' }, { label: 'Processing Periods', group: 'OPERATIONS' },
  { label: 'Data Import Centre' }, { label: 'Attendance Register' },
  { label: 'Exception Workbench' }, { label: 'Approval Inbox' },
  { label: 'Leave & OD', group: 'PAYROLL' }, { label: 'Comp-Off' },
  { label: 'Payroll Register' }, { label: 'Rule Configuration', group: 'CONFIGURATION' },
  { label: 'User & Role Management' },
  { label: 'Integration Settings' }, { label: 'Reports' }, { label: 'Audit Trail' },
]

const employees = [
  ['EMP-1042', 'Ananya Iyer', 'Finance', 'Corporate Office', 'General Shift', '09:24 AM', '06:08 PM', '8h 44m', 'Present', 'Payroll Ready'],
  ['EMP-1051', 'Arjun Kumar', 'Sales', 'Customer Locations', 'Sales Flexible', '10:12 AM', '07:48 PM', '9h 36m', 'Present', 'Payroll Ready'],
  ['EMP-1068', 'Manoj Singh', 'Projects', 'Nexora Site', 'Site Shift A', '08:52 AM', '05:28 PM', '8h 36m', 'Present', 'Payroll Ready'],
  ['EMP-1073', 'Meera Nair', 'Legal', 'Corporate Office', 'General Shift', '09:51 AM', '—', '—', 'Exception', 'Blocked'],
  ['EMP-1088', 'Ravi Patel', 'Liaison', 'External Location', 'Sales Flexible', '10:04 AM', '06:42 PM', '8h 38m', 'OD', 'Payroll Ready'],
  ['EMP-1096', 'Sneha Das', 'CRM', 'Corporate Office', 'General Shift', '10:18 AM', '06:35 PM', '8h 17m', 'Exception', 'Pending'],
  ['EMP-1104', 'Vikram Rao', 'Engineering', 'Nexora Site', 'Site Shift B', '01:58 PM', '10:22 PM', '8h 24m', 'Present', 'Payroll Ready'],
]

const exceptions = [
  ['EXC-0826-041', 'Meera Nair', '12 Aug 2026', 'Missing punch-out', 'High', 'No valid out-punch recorded after 09:51 AM.', '0.5 day LOP', 'Karthik M.', 'Pending HR'],
  ['EXC-0826-037', 'Sneha Das', '12 Aug 2026', 'Mobile login in office', 'Critical', 'Mobile attendance captured within 35m of corporate biometric device.', 'Review required', 'Priya Raman', 'Open'],
  ['EXC-0826-029', 'Nikhil Bose', '11 Aug 2026', 'GPS-radius violation', 'High', 'Login was 2.4km outside approved customer location radius.', 'Review required', 'Anand S.', 'Pending manager'],
  ['EXC-0826-018', 'Pooja Shah', '10 Aug 2026', 'Late threshold exceeded', 'Medium', 'Monthly late and permission allowance exceeded by 26 minutes.', '0.5 day LOP', 'Priya Raman', 'Open'],
  ['EXC-0826-011', 'Dev Malhotra', '09 Aug 2026', 'Sunday comp-off', 'Low', 'Worked 6h 42m on Sunday; comp-off eligibility awaits approval.', 'No impact', 'Aditi P.', 'Pending manager'],
]

function Badge({ children, tone = 'neutral' }: { children: React.ReactNode; tone?: string }) {
  return <span className={`badge ${tone}`}>{children}</span>
}

function App() {
  const [view, setView] = useState<View>('Dashboard')
  const [toast, setToast] = useState<Toast>(null)
  const [detail, setDetail] = useState<string | null>(null)
  const [importStep, setImportStep] = useState(0)
  const [processing, setProcessing] = useState(false)
  const [processed, setProcessed] = useState(false)
  const [filter, setFilter] = useState('')
  const [frozen, setFrozen] = useState(false)
  const [ruleOpen, setRuleOpen] = useState(false)
  const [showWalkthrough, setShowWalkthrough] = useState(false)
  const [persona, setPersona] = useState<Persona>('HR Manager')
  const notify = (message: string, kind: 'success' | 'warning' = 'success') => {
    setToast({ message, kind }); window.setTimeout(() => setToast(null), 3200)
  }
  const runProcessing = () => {
    setProcessing(true)
    window.setTimeout(() => { setProcessing(false); setProcessed(true); notify('Attendance processing completed for August 2026') }, 2300)
  }
  const content = useMemo(() => {
    if (view === 'Dashboard') return <Dashboard setView={setView} runProcessing={runProcessing} processed={processed} walkthrough={() => setShowWalkthrough(true)} persona={persona} />
    if (view === 'AI Insights') return <AIInsights persona={persona} setView={setView} />
    if (view === 'Processing Periods') return <Periods frozen={frozen} setFrozen={setFrozen} runProcessing={runProcessing} notify={notify} />
    if (view === 'Data Import Centre') return <ImportCentre step={importStep} setStep={setImportStep} runProcessing={runProcessing} notify={notify} />
    if (view === 'Attendance Register') return <AttendanceRegister filter={filter} setFilter={setFilter} open={setDetail} />
    if (view === 'Exception Workbench') return <ExceptionWorkbench notify={notify} />
    if (view === 'Approval Inbox') return <ApprovalInbox notify={notify} />
    if (view === 'Leave & OD') return <LeaveOD />
    if (view === 'Comp-Off') return <CompOff />
    if (view === 'Payroll Register') return <Payroll frozen={frozen} setFrozen={setFrozen} notify={notify} />
    if (view === 'Rule Configuration') return <Rules open={() => setRuleOpen(true)} />
    if (view === 'User & Role Management') return <UserRoleManagement notify={notify} />
    if (view === 'Integration Settings') return <Integrations notify={notify} />
    return <GenericPage title={view} />
  }, [view, importStep, processing, processed, filter, frozen, persona])

  return <div className="app">
    <aside className="sidebar">
      <div className="brand"><div className="brand-mark">S&P</div><div><b>SP Foundation</b><small>Attendance Intelligence</small></div></div>
      <div className="workspace"><span className="pulse"></span><span>August 2026</span><ChevronDown size={14} /></div>
      <nav>{nav.map((item, i) => <div key={item.label}>{item.group && <p className="nav-group">{item.group}</p>}<button className={view === item.label ? 'nav-item active' : 'nav-item'} onClick={() => setView(item.label)}><span className="nav-dot">{i + 1}</span>{item.label}{item.label === 'Exception Workbench' && <em>17</em>}</button></div>)}</nav>
      <div className="persona-picker"><Sparkles size={14}/><select aria-label="Active persona" value={persona} onChange={event => setPersona(event.target.value as Persona)}>{(['HR Operations Lead', 'HR Manager', 'VP of HR', 'CHRO'] as Persona[]).map(role => <option key={role}>{role}</option>)}</select></div>
      <div className="sidebar-bottom"><button className="help"><CircleHelp size={17} /> Help & support</button><div className="user-avatar">{persona === 'CHRO' ? 'AS' : persona === 'VP of HR' ? 'RM' : persona === 'HR Operations Lead' ? 'KM' : 'PR'}</div><div className="user-copy"><b>{persona === 'CHRO' ? 'Anika Sharma' : persona === 'VP of HR' ? 'Rohan Mehta' : persona === 'HR Operations Lead' ? 'Karthik Menon' : 'Priya Raman'}</b><small>{persona}</small></div><MoreHorizontal size={16} /></div>
    </aside>
    <main>
      <header><div><div className="crumb">Attendance, Absence & Payroll Automation <span>/</span> {view}</div><h1>{view}</h1></div><div className="header-actions"><button className="icon-button"><Bell size={18} /><i></i></button><button className="period-button"><CalendarDays size={16} /> 01–31 Aug 2026 <ChevronDown size={14} /></button></div></header>
      <section className="content">{content}</section>
    </main>
    {processing && <ProcessingOverlay />}
    {detail && <EmployeeDetail name={detail} close={() => setDetail(null)} />}
    {ruleOpen && <RuleDrawer close={() => setRuleOpen(false)} notify={notify} />}
    {showWalkthrough && <Walkthrough close={() => setShowWalkthrough(false)} />}
    {toast && <div className={`toast ${toast.kind}`}><CheckCircle2 size={18} />{toast.message}</div>}
  </div>
}

function Dashboard({ setView, runProcessing, processed, walkthrough, persona }: { setView: (v: View) => void; runProcessing: () => void; processed: boolean; walkthrough: () => void; persona: Persona }) {
  const metrics = [['175', 'Total employees', 'of 175 active employees'], ['168', 'Attendance processed', processed ? 'Updated just now' : '96% of period to date'], ['151', 'Payroll ready', '86% readiness'], ['17', 'Open exceptions', '5 need HR action'], ['6.5', 'Estimated LOP', 'days in current period'], ['4', 'Mobile/GPS violations', '2 critical'] ]
  return <><div className="page-top"><p>Operational overview for the active payroll period.</p><div><button className="secondary" onClick={walkthrough}><Sparkles size={16} /> Demo walkthrough</button><button className="primary" onClick={() => setView('Data Import Centre')}><Upload size={16} /> Import data</button></div></div>
    <div className="metric-grid">{metrics.map(([number, label, note], i) => <div className="metric" key={label}><div className={`metric-icon i${i}`}>{i === 3 ? <AlertTriangle size={18} /> : i === 4 ? <Clock3 size={18} /> : <Users size={18} />}</div><div><strong>{number}{label === 'Estimated LOP' && <small> days</small>}</strong><span>{label}</span><small>{note}</small></div></div>)}</div>
    <section className="ai-banner"><div className="ai-banner-icon"><Sparkles size={18}/></div><div><span>AI PRIORITY BRIEFING FOR {persona.toUpperCase()}</span><b>{persona === 'CHRO' ? 'Payroll readiness is on track, but mobile attendance exceptions need executive attention.' : persona === 'VP of HR' ? 'Three departments account for 71% of attendance risk this period.' : persona === 'HR Operations Lead' ? 'Four high-severity exceptions can be resolved before today’s HR cut-off.' : 'Focus on 5 approval items to unlock 9 payroll-ready employees.'}</b></div><button className="secondary small" onClick={() => setView('AI Insights')}>View AI insights <ArrowRight size={14}/></button></section>
    <div className="dashboard-grid">
      <section className="panel readiness"><div className="panel-head"><div><h2>Payroll readiness</h2><p>August 2026 attendance closure</p></div><Badge tone="blue">In processing</Badge></div><div className="readiness-body"><div className="donut"><b>86%</b><span>ready</span></div><div className="progress-list"><p><span><i className="green-dot"></i> Payroll ready</span><b>151 employees</b></p><p><span><i className="amber-dot"></i> Pending approvals</span><b>12 employees</b></p><p><span><i className="red-dot"></i> Blocked by exception</span><b>12 employees</b></p><button className="text-button" onClick={() => setView('Payroll Register')}>View payroll register <ArrowRight size={15} /></button></div></div></section>
      <section className="panel action-panel"><h2>Continue processing</h2><p>Complete these steps to prepare attendance for payroll.</p><button onClick={() => setView('Data Import Centre')}><span>1</span> Validate imported data <Badge tone="green">Complete</Badge></button><button onClick={runProcessing}><span>2</span> Run attendance processing <Badge tone={processed ? 'green' : 'amber'}>{processed ? 'Complete' : 'Ready'}</Badge></button><button onClick={() => setView('Exception Workbench')}><span>3</span> Resolve exceptions <Badge tone="red">17 open</Badge></button></section>
      <section className="panel chart-panel"><div className="panel-head"><div><h2>Exceptions by category</h2><p>17 exceptions require action</p></div><button className="more"><MoreHorizontal size={19}/></button></div><div className="bars">{[['Missing punch', 7], ['Mobile / GPS', 4], ['Late & permission', 3], ['Leave / OD', 2], ['Other', 1]].map(([name, n]) => <div className="bar-row" key={String(name)}><span>{name}</span><div><i style={{ width: `${Number(n) * 13}%` }}></i></div><b>{n}</b></div>)}</div></section>
      <section className="panel activity"><div className="panel-head"><div><h2>Recent activity</h2><p>Latest attendance actions</p></div><button className="text-button">View audit trail</button></div>{[['Payroll register generated','Priya Raman','12 min ago','success'],['Missing-punch regularization approved','Karthik Menon','26 min ago','blue'],['ESSL biometric import completed','System','Today, 08:15 AM','success'],['GPS violation escalated','System','Today, 08:03 AM','warning']].map(([t, u, time, tone]) => <div className="activity-row" key={t}><span className={`activity-icon ${tone}`}>{tone === 'warning' ? <AlertTriangle size={14}/> : <CheckCircle2 size={14}/>}</span><div><b>{t}</b><small>{u}</small></div><time>{time}</time></div>)}</section>
      <section className="panel sources"><div className="panel-head"><div><h2>Source synchronization</h2><p>All critical data sources are current</p></div><button className="text-button" onClick={() => setView('Integration Settings')}>Manage</button></div>{[['ESSL Biometric','Last synchronized today, 08:15 AM','Synchronized'],['greytHR','Last synchronized today, 08:30 AM','Synchronized'],['Shift Master','1 assignment warning','Needs review']].map(([name, info, status]) => <div className="source-row" key={name}><span className="source-logo">{name === 'ESSL Biometric' ? 'E' : name === 'greytHR' ? 'gH' : 'SM'}</span><div><b>{name}</b><small>{info}</small></div><Badge tone={status === 'Synchronized' ? 'green' : 'amber'}>{status}</Badge></div>)}</section>
    </div></>
}

function Periods({ frozen, setFrozen, runProcessing, notify }: any) {
  const periods = [['September 2026', '01 Sep – 30 Sep', 'Not started', '—', '0', '0%'], ['August 2026', '01 Aug – 31 Aug', frozen ? 'Frozen' : 'Processing', '168 / 175', '17', '86%'], ['July 2026', '01 Jul – 31 Jul', 'Payroll completed', '175 / 175', '0', '100%'], ['June 2026', '01 Jun – 30 Jun', 'Payroll completed', '175 / 175', '0', '100%']]
  return <><div className="page-top"><p>Manage attendance cycles, cutoffs, and payroll readiness.</p><button className="primary" onClick={() => notify('New processing period created for October 2026')}><Plus size={16}/> Create period</button></div><section className="panel table-panel"><table><thead><tr><th>Processing period</th><th>Period dates</th><th>Status</th><th>Import status</th><th>Exceptions</th><th>Payroll readiness</th><th></th></tr></thead><tbody>{periods.map((p, i) => <tr key={p[0]}><td><b>{p[0]}</b>{i === 1 && <small className="subline">Owner: Priya Raman</small>}</td><td>{p[1]}<small className="subline">Payroll cutoff: {i < 2 ? '28th' : 'Completed'}</small></td><td><Badge tone={p[2] === 'Processing' ? 'blue' : p[2] === 'Frozen' ? 'purple' : p[2] === 'Not started' ? 'neutral' : 'green'}>{p[2]}</Badge></td><td>{p[3]}</td><td>{p[4] === '0' ? <Badge tone="green">None</Badge> : <Badge tone="red">{p[4]} open</Badge>}</td><td><div className="mini-progress"><i style={{width:p[5]}}></i><span>{p[5]}</span></div></td><td>{i === 1 && <button className="secondary small" onClick={() => frozen ? (setFrozen(false), notify('Period reopened. Reason recorded in audit trail.', 'warning')) : (setFrozen(true), notify('Attendance frozen for August 2026'))}>{frozen ? 'Reopen' : 'Freeze'}</button>}</td></tr>)}</tbody></table></section><section className="two-panel"><div className="panel"><h2>August 2026 timeline</h2><div className="timeline"><p><i className="done"></i><span>Data imports</span><b>Completed</b></p><p><i className="current"></i><span>Attendance processing</span><b>In progress</b></p><p><i></i><span>Exception resolution</span><b>Due 26 Aug</b></p><p><i></i><span>Payroll export</span><b>Due 28 Aug</b></p></div><button className="primary" onClick={runProcessing}><Play size={15}/> Run processing</button></div><div className="panel"><h2>Period controls</h2><p className="muted">Attendance cutoff is 26 August 2026, 6:00 PM. Changes after cutoff require HR approval and are recorded in the audit trail.</p><div className="control-row"><span>Attendance cutoff</span><b>26 Aug, 6:00 PM</b></div><div className="control-row"><span>Payroll cutoff</span><b>28 Aug, 12:00 PM</b></div><div className="control-row"><span>Current rule version</span><b>v3.2</b></div></div></section></>
}

function ImportCentre({ step, setStep, runProcessing, notify }: any) {
  const tiles = [['Employee Master','greytHR','175','0','Synchronized'],['ESSL Biometric Punches','ESSL','3,684','12','Imported'],['Mobile Attendance','greytHR','418','4','Imported'],['Leave Records','greytHR','53','0','Imported'],['On Duty Records','greytHR','38','2','Imported'],['Regularizations','greytHR','19','1','Imported'],['Shift Assignments','CSV','175','1','Warning'],['Holiday Calendar','greytHR','12','0','Synchronized']]
  return <><div className="page-top"><p>Bring source data into the active processing period and validate before processing.</p><button className="secondary"><Settings2 size={16}/> Import history</button></div>
    {step === 0 ? <><div className="import-grid">{tiles.map(t => <button className="import-tile" key={t[0]} onClick={() => setStep(1)}><div className="tile-top"><span className="source-logo">{t[1] === 'ESSL' ? 'E' : t[1] === 'CSV' ? 'CSV' : 'gH'}</span><Badge tone={t[4] === 'Warning' ? 'amber' : 'green'}>{t[4]}</Badge></div><h3>{t[0]}</h3><p>{t[1]} · CSV, XLSX or API</p><div><span>{t[2]} records</span><span className={t[3] === '0' ? '' : 'warning-text'}>{t[3]} warnings</span></div></button>)}</div><button className="dropzone" onClick={() => setStep(1)}><FileUp size={25}/><b>Drop a source file here, or <u>browse</u></b><span>CSV or XLSX up to 25 MB · Data is validated before import</span></button></> :
      <section className="wizard panel"><div className="wizard-steps">{['Upload', 'Map columns', 'Validate & import'].map((name, i) => <div className={i + 1 === step ? 'current' : i + 1 < step ? 'complete' : ''} key={name}><span>{i + 1}</span>{name}</div>)}</div>
        {step === 1 && <div className="wizard-body"><div className="upload-ready"><CheckCircle2 size={28}/><div><h2>ESSL_August_2026_Punches.xlsx</h2><p>1.8 MB · 3,684 rows detected · ESSL Biometric Punches</p></div><button className="secondary small" onClick={() => setStep(0)}>Replace file</button></div><div className="form-grid"><label>Source system<select><option>ESSL Biometric</option></select></label><label>Processing period<select><option>August 2026</option></select></label></div><div className="wizard-actions"><button className="secondary" onClick={() => setStep(0)}>Cancel</button><button className="primary" onClick={() => setStep(2)}>Continue to mapping <ArrowRight size={15}/></button></div></div>}
        {step === 2 && <div className="wizard-body"><div className="mapping-head"><div><h2>Review column mapping</h2><p>6 of 7 mandatory fields automatically mapped with high confidence.</p></div><Badge tone="green">94% mapping confidence</Badge></div><table><thead><tr><th>Source column</th><th>Maps to application field</th><th>Confidence</th><th></th></tr></thead><tbody>{[['Employee Code','Employee ID','100%'],['Employee Name','Employee Name','100%'],['Punch Date','Attendance Date','98%'],['Punch Time','Punch Timestamp','98%'],['Device Location','Work Location','94%'],['Device ID','Attendance Device ID','96%'],['Punch Type','In / Out Indicator','86%']].map(r => <tr key={r[0]}><td><b>{r[0]}</b></td><td><select defaultValue={r[1]}><option>{r[1]}</option></select></td><td><Badge tone="green">{r[2]}</Badge></td><td><CheckCircle2 className="check" size={17}/></td></tr>)}</tbody></table><div className="wizard-actions"><button className="secondary" onClick={() => setStep(1)}>Back</button><button className="primary" onClick={() => setStep(3)}>Validate records <ShieldCheck size={15}/></button></div></div>}
        {step === 3 && <div className="wizard-body"><div className="validation-summary"><div><strong>3,684</strong><span>Total records</span></div><div><strong className="valid">3,642</strong><span>Valid</span></div><div><strong className="warn">29</strong><span>Warnings</span></div><div><strong className="invalid">13</strong><span>Rejected</span></div></div><div className="alert-box"><AlertTriangle size={18}/><div><b>13 records require review</b><p>Duplicate punch records (7), unknown site code (4), and inactive employee dates (2) will be excluded.</p></div><button className="text-button">View rejected records</button></div><div className="wizard-actions"><button className="secondary" onClick={() => setStep(2)}>Back</button><button className="primary" onClick={() => { setStep(0); notify('3,642 biometric punch records imported successfully'); runProcessing() }}>Import 3,642 valid records <ArrowRight size={15}/></button></div></div>}
      </section>}</>
}

function AttendanceRegister({ filter, setFilter, open }: any) {
  const rows = employees.filter(x => x.join(' ').toLowerCase().includes(filter.toLowerCase()))
  return <><div className="page-top"><p>Daily calculated attendance with full source and policy traceability.</p><div><button className="secondary"><Download size={16}/> Export</button><button className="primary"><Filter size={16}/> Saved filters</button></div></div><div className="filter-bar"><div className="search"><Search size={16}/><input placeholder="Search employee or ID" value={filter} onChange={e => setFilter(e.target.value)}/></div>{['12 Aug 2026', 'All departments', 'All locations', 'All shifts', 'All statuses'].map(x => <button key={x}>{x}<ChevronDown size={14}/></button>)}</div><section className="panel table-panel"><table className="register"><thead><tr><th>Employee</th><th>Department / location</th><th>Shift</th><th>First / last punch</th><th>Worked</th><th>Source</th><th>Final status</th><th>Payroll</th><th></th></tr></thead><tbody>{rows.map((r) => <tr key={r[0]} onClick={() => open(r[1])} className="clickable"><td><b>{r[1]}</b><small className="subline">{r[0]}</small></td><td>{r[2]}<small className="subline">{r[3]}</small></td><td>{r[4]}</td><td>{r[5]}<small className="subline">{r[6]}</small></td><td><b>{r[7]}</b></td><td><Badge tone={r[3].includes('Office') ? 'blue' : 'purple'}>{r[3].includes('Office') ? 'Biometric' : 'Mobile'}</Badge></td><td><Badge tone={r[8] === 'Present' ? 'green' : r[8] === 'Exception' ? 'red' : 'blue'}>{r[8]}</Badge></td><td><Badge tone={r[9] === 'Payroll Ready' ? 'green' : 'amber'}>{r[9]}</Badge></td><td><MoreHorizontal size={18}/></td></tr>)}</tbody></table></section></>
}

function ExceptionWorkbench({ notify }: any) {
  return <><div className="page-top"><p>Prioritize, route, and resolve attendance issues before payroll closure.</p><div><button className="secondary">Bulk assign</button><button className="primary" onClick={() => notify('17 records have been queued for attendance reprocessing')}>Reprocess selected</button></div></div><div className="exception-summary"><div><b>17</b><span>Open exceptions</span></div><div><b className="critical-text">2</b><span>Critical</span></div><div><b className="warning-text">5</b><span>High severity</span></div><div><b>9</b><span>Pending approvals</span></div><div><b>3.1 days</b><span>Average ageing</span></div></div><div className="filter-bar"><div className="search"><Search size={16}/><input placeholder="Search exception ID or employee"/></div>{['All types', 'All severity', 'All status', 'All departments'].map(x => <button key={x}>{x}<ChevronDown size={14}/></button>)}</div><section className="panel table-panel"><table><thead><tr><th>Exception</th><th>Employee / date</th><th>Type</th><th>Severity</th><th>Payroll impact</th><th>Assigned to</th><th>Status</th><th></th></tr></thead><tbody>{exceptions.map(x => <tr key={x[0]}><td><b>{x[0]}</b><small className="subline">Ageing: 2 days</small></td><td><b>{x[1]}</b><small className="subline">{x[2]}</small></td><td>{x[3]}<small className="subline">{x[5]}</small></td><td><Badge tone={x[4] === 'Critical' ? 'red' : x[4] === 'High' ? 'orange' : x[4] === 'Medium' ? 'amber' : 'neutral'}>{x[4]}</Badge></td><td>{x[6]}</td><td>{x[7]}</td><td><Badge tone={x[8] === 'Open' ? 'red' : 'amber'}>{x[8]}</Badge></td><td><button className="more"><MoreHorizontal size={18}/></button></td></tr>)}</tbody></table></section></>
}

function ApprovalInbox({ notify }: any) {
  const [tab, setTab] = useState('Pending My Approval')
  const requests = [['REG-2026-0812','Meera Nair','Missing punch-out','12 Aug 2026','Karthik Menon','0.5 day LOP','High'],['OD-2026-0841','Nikhil Bose','On Duty request','11 Aug 2026','Anand Shah','No impact','Medium'],['CO-2026-0188','Dev Malhotra','Comp-off credit','09 Aug 2026','Aditi Patel','No impact','Low']]
  return <><div className="page-top"><p>Review requests routed through Employee → Reporting Manager → HR workflow.</p><Badge tone="amber">9 awaiting action</Badge></div><div className="tabs">{['Pending My Approval','Submitted by Me','Approved','Rejected','Escalated'].map(x => <button className={tab === x ? 'selected' : ''} onClick={() => setTab(x)} key={x}>{x}{x === 'Pending My Approval' && <Badge tone="red">9</Badge>}</button>)}</div><section className="panel table-panel"><table><thead><tr><th>Request</th><th>Employee</th><th>Request type</th><th>Date</th><th>Rule recommendation</th><th>Payroll impact</th><th></th></tr></thead><tbody>{requests.map(r => <tr key={r[0]}><td><b>{r[0]}</b><small className="subline">Submitted 2h ago</small></td><td>{r[1]}</td><td>{r[2]}</td><td>{r[3]}</td><td><Badge tone={r[6] === 'High' ? 'red' : 'blue'}>{r[4]}</Badge></td><td>{r[5]}</td><td><div className="table-actions"><button className="approve" onClick={() => notify(`${r[0]} approved and attendance queued for reprocessing`)}>Approve</button><button className="secondary small" onClick={() => notify('Request sent back to employee', 'warning')}>Send back</button></div></td></tr>)}</tbody></table></section></>
}

function LeaveOD() { return <GenericData title="Leave & On Duty reconciliation" cols={['Employee', 'Request type', 'Dates', 'Status', 'Attendance reconciliation', 'Payroll impact']} rows={[['Asha Menon','Half-day leave','12 Aug 2026','Approved','Half day attendance reconciled','Paid leave'],['Ravi Patel','Customer visit OD','12 Aug 2026','Approved','Office to customer location verified','No impact'],['Nikhil Bose','Government office OD','11 Aug 2026','Pending','Exception generated','Review required'],['Tara Roy','Emergency leave','10 Aug 2026','Approved after cutoff','Biometric conflict detected','Review required']]} /> }
function CompOff() { return <><div className="page-top"><p>Track Sunday work eligibility, approval, credit, and expiry.</p><button className="primary">Review eligibility</button></div><div className="alert-box"><AlertTriangle size={18}/><div><b>2 comp-off balances expire within seven days</b><p>Notify employees before 19 August to use eligible balances.</p></div><button className="text-button">View balances</button></div><GenericData title="Comp-off ledger" cols={['Employee', 'Sunday worked', 'Worked duration', 'Eligibility', 'Approval', 'Expiry', 'Status']} rows={[['Dev Malhotra','09 Aug 2026','6h 42m','Eligible','Pending manager','08 Sep 2026','Pending approval'],['Riya Kapoor','20 Jul 2026','7h 18m','Approved','HR approved','19 Aug 2026','Expiring soon'],['Aman Gupta','12 Jul 2026','6h 05m','Credited','Complete','11 Aug 2026','Expired']]} /></> }

function Payroll({ frozen, setFrozen, notify }: any) { return <><div className="page-top"><p>Employee-level payable attendance after policy reconciliation and approved exceptions.</p><div><button className="secondary" onClick={() => notify('Payroll register exported as XLSX') }><Download size={16}/> Export Excel</button><button className="primary" onClick={() => { if (!frozen) notify('Resolve critical exceptions and freeze attendance before sending to payroll', 'warning'); else notify('Payroll-ready attendance sent to greytHR') }}>Send to payroll</button></div></div><div className="payroll-metrics"><div><b>151</b><span>Employees payroll ready</span></div><div><b className="critical-text">12</b><span>Blocked by exceptions</span></div><div><b>4,238.5</b><span>Total payable days</span></div><div><b>6.5</b><span>Total LOP days</span></div><div><b>14</b><span>Comp-off utilized</span></div></div><GenericData title="Payroll attendance register" cols={['Employee', 'Department', 'Working days', 'Present', 'Paid leave', 'LOP', 'Payable days', 'Readiness']} rows={[['Ananya Iyer · EMP-1042','Finance','22','21','1','0','31','Payroll ready'],['Arjun Kumar · EMP-1051','Sales','22','22','0','0','31','Payroll ready'],['Meera Nair · EMP-1073','Legal','22','20.5','1','0.5','30.5','Blocked'],['Sneha Das · EMP-1096','CRM','22','21','0','0','30','Pending']]} /><div className="freeze-row panel"><div><ShieldCheck size={22}/><div><b>Freeze attendance for payroll</b><p>Locks calculated attendance and writes a permanent audit entry.</p></div></div><button className={frozen ? 'secondary' : 'primary'} onClick={() => { setFrozen(!frozen); notify(frozen ? 'Attendance period reopened for correction' : 'Attendance frozen for payroll') }}>{frozen ? 'Reopen attendance' : 'Freeze attendance'}</button></div></> }

function Rules({ open }: any) { const rules = [['Office timings','General Shift','09:30 AM – 06:00 PM','Active'],['Minimum working hours','Corporate Office','8h 30m','Active'],['Late & permission allowance','All employees','4h per payroll month','Active'],['Missing punch detection','All employees','Require valid in + out','Active'],['Mobile attendance','Sales & Liaison','GPS + approved location','Active'],['Sunday comp-off','All eligible groups','Minimum 6h; valid for 30 days','Active']]; return <><div className="page-top"><p>No-code policy configuration with version history and effective-date controls.</p><button className="primary" onClick={open}><Plus size={16}/> Create rule</button></div><div className="rule-note"><Sparkles size={18}/><div><b>Current ruleset: August 2026 · Version 3.2</b><p>Changes are versioned, require approval when applicable, and take effect only from the configured date.</p></div></div><section className="panel table-panel"><table><thead><tr><th>Rule</th><th>Applicable group</th><th>Current value</th><th>Effective date</th><th>Version</th><th>Status</th><th></th></tr></thead><tbody>{rules.map(r => <tr key={r[0]}><td><b>{r[0]}</b><small className="subline">Last modified by Priya Raman</small></td><td>{r[1]}</td><td>{r[2]}</td><td>01 Aug 2026</td><td>v3.2</td><td><Badge tone="green">{r[3]}</Badge></td><td><button className="secondary small" onClick={open}>Edit rule</button></td></tr>)}</tbody></table></section></> }

function Integrations({ notify }: any) { return <><div className="page-top"><p>Simulated source-system connections and scheduled data synchronization.</p><button className="primary" onClick={() => notify('All integrations queued for synchronization')}>Sync all sources</button></div><div className="integration-grid">{[['ESSL biometric','API or scheduled file','Today, 08:15 AM','3,684 punch records'],['greytHR','REST API','Today, 08:30 AM','Employee, leave, OD, mobile attendance'],['Secure file transfer','SFTP','Yesterday, 06:00 PM','Shift assignment file'],['Manual CSV / XLSX','File upload','Today, 09:14 AM','Holiday calendar']].map((x,i) => <section className="panel integration-card" key={x[0]}><div className="tile-top"><span className="large-source">{i === 0 ? 'E' : i === 1 ? 'gH' : i === 2 ? 'SFTP' : 'CSV'}</span><Badge tone="green">Connected</Badge></div><h2>{x[0]}</h2><p>{x[1]}</p><div className="integration-detail"><span>Last successful sync</span><b>{x[2]}</b><span>Records received</span><b>{x[3]}</b></div><div><button className="secondary small" onClick={() => notify(`${x[0]} connection test successful`)}>Test connection</button><button className="text-button" onClick={() => notify(`${x[0]} synchronization started`)}>Sync now</button></div></section>)}</div></> }
function AIInsights({ persona, setView }: { persona: Persona; setView: (view: View) => void }) {
  const insights: Record<Persona, { headline: string; summary: string; stats: string[][]; actions: string[][] }> = {
    'HR Operations Lead': { headline: 'Resolve 4 high-severity items before the 6:00 PM cut-off', summary: 'Exception volume is within operational tolerance, but unresolved mobile and punch anomalies could delay individual payroll records.', stats: [['4', 'High-severity items'], ['9', 'Approvals awaiting action'], ['3.1d', 'Average exception ageing']], actions: [['Review mobile attendance violations', '2 critical GPS or office-premise violations need evidence review.'], ['Clear missing-punch queue', '3 records have complete source evidence ready for correction.'], ['Assign pending OD requests', '2 requests remain unassigned beyond the manager SLA.']] },
    'HR Manager': { headline: 'Five approvals can unlock nine payroll-ready employees', summary: 'Most attendance records are complete. Your highest-leverage action is to approve the regularizations and OD requests already recommended by the rule engine.', stats: [['151', 'Payroll-ready employees'], ['5', 'My pending approvals'], ['6.5', 'Estimated LOP days']], actions: [['Approve Meera Nair regularization', 'Missing punch-out has a corroborating access record.'], ['Review CRM mobile login pattern', 'Two repeat office-premise mobile logins occurred this month.'], ['Escalate late allowance exception', 'Pooja Shah has exceeded the configurable 4-hour allowance.']] },
    'VP of HR': { headline: 'Attendance risk is concentrated in three departments', summary: 'Sales, CRM, and Legal account for 71% of open exceptions. The pattern suggests targeted manager communication will reduce next-month reconciliation effort.', stats: [['71%', 'Risk in 3 departments'], ['86%', 'Payroll readiness'], ['4', 'Mobile/GPS violations']], actions: [['Review department risk pattern', 'Sales has high OD volume; CRM has recurring mobile attendance exceptions.'], ['Sponsor manager accountability', '9 approvals are past their first response target.'], ['Assess policy adoption', 'General Shift late allowance is the main LOP driver this month.']] },
    'CHRO': { headline: 'Payroll closure is on track with controllable policy risks', summary: 'The organization is 86% payroll ready. Exceptions are visible and auditable, with no systemic biometric integration issue detected this period.', stats: [['86%', 'Payroll readiness'], ['17', 'Open exceptions'], ['0', 'Unreconciled source feeds']], actions: [['Monitor payroll closure confidence', 'Resolve two critical attendance-control exceptions before authorizing payroll freeze.'], ['Review workforce mobility trend', 'Mobile usage is appropriate for field teams but needs tighter controls at corporate office.'], ['Track policy impact', 'Current late and permission rule produces 6.5 estimated LOP days across the period.']] },
  }
  const current = insights[persona]
  return <><div className="page-top"><p>AI-generated operational signals grounded in the active attendance processing period.</p><Badge tone="purple">Simulated AI analysis</Badge></div>
    <section className="ai-hero"><div><span>LEADERSHIP BRIEFING · {persona.toUpperCase()}</span><h2>{current.headline}</h2><p>{current.summary}</p><button className="primary" onClick={() => setView(persona === 'HR Manager' ? 'Approval Inbox' : persona === 'HR Operations Lead' ? 'Exception Workbench' : 'Payroll Register')}>Take recommended action <ArrowRight size={15}/></button></div><div className="ai-orbit"><Sparkles size={31}/><small>AI</small></div></section>
    <div className="insight-stats">{current.stats.map(stat => <div className="panel" key={stat[1]}><b>{stat[0]}</b><span>{stat[1]}</span></div>)}</div>
    <div className="ai-layout"><section className="panel"><div className="panel-head"><div><h2>Recommended actions</h2><p>Prioritized by payroll impact and urgency</p></div><Badge tone="blue">Confidence: high</Badge></div>{current.actions.map((action, index) => <div className="ai-action" key={action[0]}><span>{index + 1}</span><div><b>{action[0]}</b><p>{action[1]}</p></div><ArrowRight size={16}/></div>)}</section><section className="panel ai-explanation"><div className="panel-head"><div><h2>Why the AI flagged this</h2><p>Traceable evidence, not a black box</p></div></div><div><ShieldCheck size={18}/><p>Insights use attendance outcomes, approval ageing, source-data quality, configured policy thresholds, and payroll impact from the August 2026 sample data.</p></div><div><CheckCircle2 size={18}/><p>Every recommendation links back to the underlying employee records and never changes attendance or payroll automatically.</p></div><button className="secondary small">View decision methodology</button></section></div></>
}
function UserRoleManagement({ notify }: { notify: (message: string, kind?: 'success' | 'warning') => void }) {
  const [users, setUsers] = useState([
    ['Priya Raman', 'priya.raman@spf.in', 'HR Manager', 'HR Operations', 'Active'],
    ['Karthik Menon', 'karthik.menon@spf.in', 'HR Operations Lead', 'HR Operations', 'Active'],
    ['Rohan Mehta', 'rohan.mehta@spf.in', 'VP of HR', 'Leadership', 'Active'],
    ['Anika Sharma', 'anika.sharma@spf.in', 'CHRO', 'Leadership', 'Active'],
    ['Aditi Patel', 'aditi.patel@spf.in', 'Reporting Manager', 'Projects', 'Active'],
    ['Anand Shah', 'anand.shah@spf.in', 'Reporting Manager', 'Sales', 'Suspended'],
  ])
  const toggleStatus = (email: string) => { setUsers(items => items.map(user => user[1] === email ? [...user.slice(0, 4), user[4] === 'Active' ? 'Suspended' : 'Active'] : user)); notify(`Access status updated for ${email}`) }
  return <><div className="page-top"><p>Manage access, persona-based dashboards, approval authority, and attendance data permissions.</p><button className="primary" onClick={() => notify('Invitation created for a new user')}><Plus size={16}/> Invite user</button></div>
    <div className="access-summary"><div><Users size={20}/><b>28</b><span>Active users</span></div><div><ShieldCheck size={20}/><b>6</b><span>Defined roles</span></div><div><Clock3 size={20}/><b>3</b><span>Pending invitations</span></div><div><AlertTriangle size={20}/><b>1</b><span>Access review due</span></div></div>
    <div className="role-grid"><section className="panel"><div className="panel-head"><div><h2>Role permissions</h2><p>What each persona can access</p></div><button className="text-button">Manage roles</button></div>{[['HR Operations Lead', 'Exceptions, processing, imports', 'Resolve and assign operational work'], ['HR Manager', 'Approvals, attendance, payroll register', 'Approve corrections and prepare payroll'], ['VP of HR', 'Insights, reports, policy review', 'Monitor department risks and policy impact'], ['CHRO', 'Executive insights, governance, audit', 'Oversee closure confidence and controls']].map(role => <div className="role-row" key={role[0]}><span className="role-mark">{role[0].split(' ').map(word => word[0]).join('').slice(0, 2)}</span><div><b>{role[0]}</b><small>{role[1]}</small></div><p>{role[2]}</p></div>)}</section><section className="panel access-governance"><h2>Access governance</h2><p>Quarterly access review is due for one suspended manager account.</p><div className="governance-meter"><i></i><b>96%</b><span>review completion</span></div><button className="secondary small" onClick={() => notify('Access review package generated')}>Start access review</button></section></div>
    <section className="panel table-panel user-table"><div className="panel-head"><div><h2>Users</h2><p>Role assignments and access status</p></div><div><button className="secondary small"><Filter size={14}/> Filter</button><button className="secondary small"><Download size={14}/> Export</button></div></div><table><thead><tr><th>User</th><th>Role</th><th>Scope</th><th>Last active</th><th>Status</th><th></th></tr></thead><tbody>{users.map(user => <tr key={user[1]}><td><b>{user[0]}</b><small className="subline">{user[1]}</small></td><td><Badge tone={user[2].includes('CHRO') || user[2].includes('VP') ? 'purple' : user[2].includes('Manager') ? 'blue' : 'green'}>{user[2]}</Badge></td><td>{user[3]}</td><td>Today, 10:24 AM</td><td><Badge tone={user[4] === 'Active' ? 'green' : 'amber'}>{user[4]}</Badge></td><td><button className="secondary small" onClick={() => toggleStatus(user[1])}>{user[4] === 'Active' ? 'Suspend' : 'Restore'}</button></td></tr>)}</tbody></table></section></>
}
function GenericPage({ title }: { title: string }) { return <div className="empty-panel panel"><div className="empty-icon"><Sparkles size={24}/></div><h2>{title}</h2><p>This presentation-ready operational view is available through the left navigation. Use the dashboard to continue the end-to-end attendance journey.</p></div> }
function GenericData({ title, cols, rows }: { title: string; cols: string[]; rows: string[][] }) { return <section className="panel table-panel generic-data"><div className="panel-head"><div><h2>{title}</h2><p>August 2026 processing period</p></div><button className="secondary small"><Download size={14}/> Export</button></div><table><thead><tr>{cols.map(c => <th key={c}>{c}</th>)}</tr></thead><tbody>{rows.map((r,i) => <tr key={i}>{r.map((v,j) => <td key={j}>{j === 0 ? <b>{v}</b> : v.includes('Approved') || v === 'Payroll ready' ? <Badge tone="green">{v}</Badge> : v.includes('Pending') || v.includes('Review') || v === 'Blocked' ? <Badge tone="amber">{v}</Badge> : v === 'Expired' || v === 'Expiring soon' ? <Badge tone="red">{v}</Badge> : v}</td>)}</tr>)}</tbody></table></section> }

function ProcessingOverlay() { const [stage, setStage] = useState(0); const stages = ['Employee & employment validation','Work location and calendar identification','Shift identification','Biometric and mobile reconciliation','Leave and OD validation','Working-hours calculation','Exception generation','Final attendance classification']; useState(() => { const timer = window.setInterval(() => setStage(s => Math.min(s + 1, 7)), 280); return () => window.clearInterval(timer) }); return <div className="overlay"><section className="process-modal"><div className="processing-icon"><Settings2 size={28}/></div><h2>Running attendance processing</h2><p>Applying August 2026 ruleset to 168 employee attendance records.</p><div className="process-progress"><i style={{ width: `${(stage + 1) * 12.5}%` }}></i></div><div className="process-stages">{stages.map((x, i) => <p key={x} className={i < stage ? 'done' : i === stage ? 'active' : ''}>{i < stage ? <CheckCircle2 size={16}/> : <span>{i + 1}</span>}{x}<em>{i < stage ? 'Complete' : i === stage ? 'Processing' : 'Queued'}</em></p>)}</div></section></div> }
function EmployeeDetail({ name, close }: { name: string; close: () => void }) { return <div className="detail-panel"><div className="detail-head"><div><small>EMPLOYEE-DAY ATTENDANCE</small><h2>{name}</h2><p>12 August 2026 · Sales · Customer locations</p></div><button className="icon-button" onClick={close}><X size={18}/></button></div><div className="detail-status"><Badge tone="green">Present</Badge><span>Payroll impact: <b>No deduction</b></span></div><div className="timeline-detail"><h3>Attendance timeline</h3><p><i></i><b>10:12 AM</b><span>Mobile login · Approved customer location</span></p><p><i></i><b>10:30 AM</b><span>Approved OD begins · Customer visit</span></p><p><i></i><b>07:48 PM</b><span>Mobile logout · GPS verified</span></p><p><i className="final"></i><b>9h 36m</b><span>Final worked duration</span></p></div><div className="why"><div><Sparkles size={17}/><b>Why this status?</b></div><p>Employee arrived 42 minutes after standard office start time. An approved customer-visit OD existed, GPS was within the approved location radius, and the employee completed 9 hours 36 minutes. The day is classified as Present with no payroll deduction.</p></div><div className="detail-grid"><div><span>Assigned policy</span><b>Sales Flexible Schedule</b></div><div><span>Attendance source</span><b>Mobile login</b></div><div><span>OD request</span><b>Approved</b></div><div><span>Rule version</span><b>v3.2</b></div></div><button className="primary full" onClick={close}>Close explanation</button></div> }
function RuleDrawer({ close, notify }: any) { return <div className="detail-panel rule-drawer"><div className="detail-head"><div><small>EDIT RULE</small><h2>Late & permission allowance</h2><p>Applicable to all employees</p></div><button className="icon-button" onClick={close}><X size={18}/></button></div><label>Rule condition<select defaultValue="Combined late coming and permission"><option>Combined late coming and permission</option></select></label><label>Monthly allowance<input defaultValue="4 hours"/></label><label>Outcome after threshold<input defaultValue="Every additional 4h = 0.5 day LOP"/></label><label>Effective date<input type="date" defaultValue="2026-08-01"/></label><div className="rule-note compact"><ShieldCheck size={17}/><p>This allowance resets at the beginning of every payroll month. This assumption is configurable.</p></div><button className="primary full" onClick={() => { close(); notify('Rule version 3.3 saved for approval') }}>Save new rule version</button></div> }
function Walkthrough({ close }: { close: () => void }) { const [i, setI] = useState(0); const slides = [['Attendance intelligence layer','ESSL and greytHR remain your source systems. This application consolidates, validates, and applies your policies before payroll.'],['Import and validate','Files and integrations are checked for structure, duplicates, inactive employees, missing shifts, and source quality before calculation.'],['Explainable decisions','Every attendance result is traceable to source records, applied policy, approval history, and a plain-language explanation.'],['Payroll-ready output','Only exceptions require attention. Once critical exceptions are resolved, attendance is frozen and sent to payroll with a complete audit trail.']]; return <div className="overlay"><section className="walkthrough"><button className="close-walk" onClick={close}><X size={18}/></button><span className="walk-count">DEMO WALKTHROUGH · {i + 1} / {slides.length}</span><div className="walk-icon"><Sparkles size={30}/></div><h2>{slides[i][0]}</h2><p>{slides[i][1]}</p><div className="walk-dots">{slides.map((_, j) => <i className={i === j ? 'selected' : ''} key={j}/>)}</div><button className="primary" onClick={() => i === slides.length - 1 ? close() : setI(i + 1)}>{i === slides.length - 1 ? 'Finish walkthrough' : 'Continue'} <ArrowRight size={16}/></button></section></div> }

export default App
